import os
from gps3 import gps3

gps_socket = gps3.GPSDSocket()
data_stream = gps3.DataStream()
gps_socket.connect()
gps_socket.watch()

for new_data in gps_socket:
    if new_data:
        os.system('clear')
        data_stream.unpack(new_data)
        print('device = ', data_stream.TPV.get('device'))
        print('status = ', data_stream.TPV.get('status'))
        print('mode = ', data_stream.TPV.get('mode'))
        print('time = ', data_stream.TPV.get('time'))
        print('ept = ', data_stream.TPV.get('ept'))
        print('lat = ', data_stream.TPV.get('lat'))
        print('lon = ', data_stream.TPV.get('lon'))
        print('alt = ', data_stream.TPV.get('alt'))
        print('epx = ', data_stream.TPV.get('epx'))
        print('epy = ', data_stream.TPV.get('epy'))
        print('epv = ', data_stream.TPV.get('epv'))
        print('track = ', data_stream.TPV.get('track'))
        print('speed = ', data_stream.TPV.get('speed'))
        print('epd = ', data_stream.TPV.get('epd'))
        print('eps = ', data_stream.TPV.get('eps'))
        print('epc = ', data_stream.TPV.get('epc'))
        print('-------------------------------')
        print('time = ', data_stream.SKY.get('time'))
        print('xdop = ', data_stream.SKY.get('xdop'))
        print('ydop = ', data_stream.SKY.get('ydop'))
        print('vdop = ', data_stream.SKY.get('vdop'))
        print('tdop = ', data_stream.SKY.get('tdop'))
        print('hdop = ', data_stream.SKY.get('hdop'))
        print('gdop = ', data_stream.SKY.get('gdop'))
        print('satellites = ', data_stream.SKY.get('satellites'))
        print('# satellites = ', len(data_stream.SKY.get('satellites')))
